apiVersion: v1
kind: Service
metadata:
  name: abc-service
spec:
  type: NodePort
  selector:
    app: shopping-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001